### ISSUE TITLE
UE5.3

### ISSUE THREAD

**Issue by Imaginary-Narwhal** [DarknessFX/UEPlaystationGamepad#2]
I downloaded and opened the project. After running the d-pad and the option, share and touchpad all work. But that's all. None of the Axis work, none of the buttons or should buttons work. I do have a gen 1 controller.

I can't seem to figure out how to get it to work however.

**Comment by Imaginary-Narwhal** [comment]
I put an "any key" output to print the name of the input and it was showing GenericUSBGamepad Axis 1 thru 8 going all the time, even when I unplugged my controller. So I decided to reboot and see what happens. After that, none of the inputs work. The controller is plugged in, but no output from my any key, and none of the buttons work on the hud. Will poke around later, maybe I screwed something up.

**Comment by DarknessFX** [comment]
Thank you for your feedback.
Indeed, this is an expected issue because the 1st Gen isn't configured to work yet.
I have made a custom project to log the Button and Axis from the 1st Gen, if possible you can download the project here:
https://dfx.lv/wp-content/uploads/UEPlaystationGamepad_Test.zip

If you play this project version it will ask you to press each button/axis once and later you can paste here the OUTPUT LOG Window results. With this information in hands I can update the main project to support 1st Gen DS4 Gamepads.
